### ISSUE TITLE
libdart6-collision-ode missing version 6.3

### ISSUE THREAD

**Issue by evanglasgow** [dartsim/dart#925] opened 2017-10-05 19:47 UTC
It looks like libdart6-collision-ode(-dev) is missing a version bump to 6.3. After updating to 6.3 from the PPA I've noticed linker issues with the ODE collision library looking for version 6.2 of DART.

**Comment by jslee02** [comment] 2017-10-05 19:51
Thanks for the report. Which Ubuntu distribution are you on? `libdart6-collision-ode-dev` is available on Xenial and Zesty but Trusty for both of DART 6.2 and 6.3. This is because `libode-dev` on Trusty is too old.

**Comment by evanglasgow** [comment] 2017-10-05 19:54
I'm on Xenial. Strange that I seem to show 6.2 available for libdart6-collision-ode-dev only.

**Comment by jslee02** [comment] 2017-10-05 20:57
I confirmed that it's missing. Let me update here once it's fixed.

**Comment by jslee02** [comment] 2017-10-05 23:23
Fixed! Please close this issue if it works for you as well.

**Closed** 2017-10-06 13:07 UTC
