### ISSUE TITLE
Problem with angular momentum conservation in dart 4.3.4

### ISSUE THREAD

**Issue by scpeters** [dartsim/dart#424] opened 2015-06-26 18:41 UTC
Initially reported as [gazebo issue 1487](https://bitbucket.org/osrf/gazebo/issue/1487/dart-has-lower-accuracy-on-angular). We added a [GetWorldAngularMomentum test](https://bitbucket.org/osrf/gazebo/src/3e1e86e456efae91240b61a42238e437ab07bdad/test/integration/physics_link.cc#cl-241), but we had to [relax the tolerances for dart](https://bitbucket.org/osrf/gazebo/src/3e1e86e456efae91240b61a42238e437ab07bdad/test/integration/physics_link.cc#cl-310). This may be related to #229; I'm not sure. Also, I haven't run the test with dart 5.

**Comment by jslee02** [comment] 2015-10-15 04:33
This issue should be resolved by #518. I will check the gazebo test again and also add an test to DART to make sure this is kept being resolved.

**Comment by scpeters** [comment] 2015-10-15 20:55
I believe #518 improved angular momentum conservation, but the linear velocity and position seem to be much less accurate now.

**Comment by scpeters** [comment] 2015-10-15 21:17
My last comment is based on a test using https://github.com/scpeters/benchmark

**Comment by acxz** [comment] 2019-02-17 22:15
I was just going through DART issues and was wondering if we could close this issue, since it is on 4.3.4 (an outdated version).
The issue could be kept if the problem persists in the current stable branch of DART tho.

**Comment by mxgrey** [comment] 2019-02-18 01:55
We should probably have a regression test for the issue and see that the regression test passes before we consider closing it.

**Comment by jslee02** [comment] 2019-02-18 02:04
As a note, probably this is related to https://github.com/dartsim/dart/issues/1193.

**Comment by jslee02** [comment] 2019-07-14 23:49
Closing this issue in favor of #1193, which I'm still working on.

**Closed by jslee02** 2019-07-14 23:49 UTC
